"""Write paper/latex/numbers.tex: LaTeX macros (\\rs<NAME>) for headline numbers read from experiments/results.

    python scripts/paper_numbers.py [--results experiments/results] [--out paper/latex/numbers.tex]

Keeps the manuscript honest: every number that appears in prose more than once is a macro
generated from summary.csv, so re-running a sweep cannot leave a stale figure in the text.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


def _fmt(x: float, nd: int = 1) -> str:
    return f"{x:.{nd}f}"


def _wilcoxon_p(a, b) -> float:
    """Two-sided exact Wilcoxon signed-rank p over paired per-scene values (scenes are the unit)."""
    from scipy.stats import wilcoxon

    return float(wilcoxon(a, b, alternative="two-sided", method="exact").pvalue)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="experiments/results")
    ap.add_argument("--out", default="paper/latex/numbers.tex")
    args = ap.parse_args()
    df = pd.read_csv(Path(args.results) / "summary.csv")
    e1 = df[df.experiment == "exp1_depth_source"].groupby("run_name")
    mean, std = e1.mean(numeric_only=True), e1.std(numeric_only=True)
    e5 = df[df.experiment == "exp5_lidar_confidence"].groupby("run_name").mean(numeric_only=True)

    def cm(run, col="chamfer"):
        return mean.loc[run, col] * 100, std.loc[run, col] * 100

    lines = ["% generated by scripts/paper_numbers.py — do not edit", ""]

    def macro(name, value):
        lines.append(f"\\newcommand{{\\rs{name}}}{{{value}}}")

    for run, tag in (("gt", "GT"), ("lidar", "LIDAR"), ("mono_oracle", "ORACLE"), ("mono_sparse", "SPARSE"),
                     ("mono_scene", "SCENE"), ("mono_metric", "METRIC")):
        if run not in mean.index:
            continue
        mu, sd = cm(run)
        macro(f"{tag}CM", _fmt(mu))
        macro(f"{tag}SD", _fmt(sd))
        macro(f"{tag}F", _fmt(mean.loc[run, "fscore@0.05"], 2))
        macro(f"{tag}ABSREL", _fmt(mean.loc[run, "abs_rel"], 3))
        macro(f"{tag}DELTAONE", _fmt(mean.loc[run, "delta1"], 3))
        macro(f"{tag}RMSE", _fmt(mean.loc[run, "rmse"] * 100, 1))
        macro(f"{tag}ACC", _fmt(mean.loc[run, "accuracy"] * 100))
        macro(f"{tag}COMP", _fmt(mean.loc[run, "completeness"] * 100))
        for tau, word in (("0.02", "two"), ("0.05", "five"), ("0.1", "ten")):   # no digits in macro names
            macro(f"{tag}F{word}", _fmt(mean.loc[run, f"fscore@{tau}"], 2))
            macro(f"{tag}R{word}", _fmt(mean.loc[run, f"recall@{tau}"], 2))
    # per-scene Chamfer in the paper's Table 4.1 order -> \rsSPARSEa ... \rsSPARSEf ("---" if not run yet)
    order = ["42444474", "47333774", "47115299", "42897743", "47429736", "45261556"]

    def per_scene(experiment: str, run: str) -> pd.Series:
        sub = df[(df.experiment == experiment) & (df.run_name == run)]
        return sub.set_index(sub.scene.astype(str))["chamfer"]

    for exp, runs in (("exp1_depth_source", (("gt", "GT"), ("lidar", "LIDAR"), ("mono_oracle", "ORACLE"),
                                             ("mono_sparse", "SPARSE"), ("mono_scene", "SCENE"),
                                             ("mono_metric", "METRIC"))),
                      ("exp6_finetune", (("mono_ft_faro", "FTFARO"), ("mono_ft_lidar", "FTLIDAR"),
                                         ("mono_ft_lidar_all", "FTLIDARALL"),
                                         ("mono_depth_pro", "DEPTHPRO")))):
        for run, tag in runs:
            col = per_scene(exp, run)
            for letter, scene in zip("abcdef", order, strict=True):
                macro(f"{tag}{letter}", _fmt(col[scene] * 100) if scene in col.index else "---")

    def gap(run_a: str, run_b: str) -> tuple[float, float]:
        """mean +- sd of the per-scene difference (cm) — paired, unlike the difference of two means."""
        d = (per_scene("exp1_depth_source", run_a) - per_scene("exp1_depth_source", run_b)) * 100
        return float(d.mean()), float(d.std())

    if "mono_sparse" in mean.index:
        macro("SPARSEGAP", _fmt(cm("mono_sparse")[0] - cm("mono_oracle")[0]))
        macro("SPARSEGAPLIDAR", _fmt(cm("mono_sparse")[0] - cm("lidar")[0]))
        macro("SPARSEVSSCENE", _fmt(cm("mono_scene")[0] / cm("mono_sparse")[0]))
    for (a, b), tag in ((("lidar", "gt"), "LIDARGAPGT"), (("mono_oracle", "lidar"), "ORACLEGAPLIDAR")):
        mu, sd = gap(a, b)
        macro(f"{tag}CM", _fmt(mu, 2))
        macro(f"{tag}SD", _fmt(sd, 2))
    for run, tag in (("lidar_conf1", "CONFONE"), ("lidar_conf2", "CONFTWO"),
                     ("lidar_w012", "WZOT"), ("lidar_w124", "WOTF")):
        if run in e5.index:
            macro(f"{tag}CM", _fmt(e5.loc[run, "chamfer"] * 100, 2))
            macro(f"{tag}F", _fmt(e5.loc[run, "fscore@0.05"], 2))
            macro(f"{tag}ACC", _fmt(e5.loc[run, "accuracy"] * 100, 2))
            macro(f"{tag}COMP", _fmt(e5.loc[run, "completeness"] * 100, 2))
    # Exp6 (ADR-013): the ARKitScenes fine-tunes, RGB-only, no alignment
    e6 = df[df.experiment == "exp6_finetune"].groupby("run_name")
    m6, s6 = e6.mean(numeric_only=True), e6.std(numeric_only=True)
    for run, tag in (("mono_ft_faro", "FTFARO"), ("mono_ft_lidar", "FTLIDAR"),
                     ("mono_ft_lidar_all", "FTLIDARALL"), ("mono_depth_pro", "DEPTHPRO")):
        if run not in m6.index:
            continue
        macro(f"{tag}CM", _fmt(m6.loc[run, "chamfer"] * 100))
        macro(f"{tag}SD", _fmt(s6.loc[run, "chamfer"] * 100))
        macro(f"{tag}F", _fmt(m6.loc[run, "fscore@0.05"], 2))
        macro(f"{tag}ABSREL", _fmt(m6.loc[run, "abs_rel"], 3))
        macro(f"{tag}DELTAONE", _fmt(m6.loc[run, "delta1"], 3))
        for tau, word in (("0.02", "two"), ("0.05", "five"), ("0.1", "ten")):
            macro(f"{tag}R{word}", _fmt(m6.loc[run, f"recall@{tau}"], 2))
    # the paper's main comparison (ADR-014): R3 (LiDAR teacher, 24 scenes) vs the same checkpoint pretrained
    if "mono_ft_lidar_all" in m6.index and "mono_metric" in m6.index:
        pre, ft = per_scene("exp6_finetune", "mono_metric"), per_scene("exp6_finetune", "mono_ft_lidar_all")
        d = (pre - ft) * 100
        macro("MAINGAIN", _fmt(m6.loc["mono_metric", "chamfer"] / m6.loc["mono_ft_lidar_all", "chamfer"], 1))
        macro("MAINDIFFCM", _fmt(d.mean()))
        macro("MAINDIFFSD", _fmt(d.std()))
        macro("MAINWINS", str(int((d > 0).sum())))
        macro("MAINN", str(len(d)))
        macro("MAINP", _fmt(_wilcoxon_p(pre.values, ft.values), 3))
        macro("MAINFGAIN", _fmt(m6.loc["mono_ft_lidar_all", "fscore@0.05"] / m6.loc["mono_metric", "fscore@0.05"], 0))
        macro("METRICSIXABSREL", _fmt(m6.loc["mono_metric", "abs_rel"], 3))
        macro("METRICSIXDELTAONE", _fmt(m6.loc["mono_metric", "delta1"], 3))
        macro("METRICSIXRMSE", _fmt(m6.loc["mono_metric", "rmse"] * 100))
        macro("FTLIDARALLRMSE", _fmt(m6.loc["mono_ft_lidar_all", "rmse"] * 100))
        gap_sparse = m6.loc["mono_ft_lidar_all", "chamfer"] - mean.loc["mono_sparse", "chamfer"]
        macro("FTALLGAPSPARSE", _fmt(gap_sparse * 100))
        macro("FTLIDARALLACC", _fmt(m6.loc["mono_ft_lidar_all", "accuracy"] * 100))
        macro("FTLIDARALLCOMP", _fmt(m6.loc["mono_ft_lidar_all", "completeness"] * 100))
        # per-scene AbsRel (Table 4.1 order) for the main per-scene table -> \rsMETRICARa ... \rsFTALLARf
        for run, tag in (("mono_metric", "METRICAR"), ("mono_ft_lidar_all", "FTALLAR")):
            sub = df[(df.experiment == "exp6_finetune") & (df.run_name == run)]
            col = sub.set_index(sub.scene.astype(str))["abs_rel"]
            for letter, scene in zip("abcdef", order, strict=True):
                macro(f"{tag}{letter}", _fmt(col[scene], 3) if scene in col.index else "---")

    # Exp7 (ADR-014): 2D only, Validation-fold scenes never used for anything else
    e7 = df[df.experiment == "exp7_valfold_2d"]
    if not e7.empty:
        g7 = e7.groupby("run_name")
        m7, s7 = g7.mean(numeric_only=True), g7.std(numeric_only=True)
        for run, tag in (("mono_metric", "VMETRIC"), ("mono_ft_lidar_all", "VFTALL"), ("lidar", "VLIDAR")):
            if run not in m7.index:
                continue
            macro(f"{tag}ABSREL", _fmt(m7.loc[run, "abs_rel"], 3))
            macro(f"{tag}ABSRELSD", _fmt(s7.loc[run, "abs_rel"], 3))
            macro(f"{tag}DELTAONE", _fmt(m7.loc[run, "delta1"], 3))
            macro(f"{tag}DELTAONESD", _fmt(s7.loc[run, "delta1"], 3))
            macro(f"{tag}RMSE", _fmt(m7.loc[run, "rmse"] * 100))
        if {"mono_metric", "mono_ft_lidar_all"} <= set(m7.index):
            by = e7.pivot_table(index=e7.scene.astype(str), columns="run_name", values=["abs_rel", "delta1"])
            pre, ft = by[("abs_rel", "mono_metric")], by[("abs_rel", "mono_ft_lidar_all")]
            macro("VN", str(len(by)))
            macro("VFRAMES", f"{int(e7[e7.run_name == 'mono_ft_lidar_all'].n_frames.sum()):,}".replace(",", "{,}"))
            macro("VWINS", str(int((ft < pre).sum())))
            macro("VWINSDELTA", str(int((by[("delta1", "mono_ft_lidar_all")] > by[("delta1", "mono_metric")]).sum())))
            macro("VP", _fmt(_wilcoxon_p(pre.values, ft.values), 4) if len(by) >= 6 else "---")
            macro("VGAIN", _fmt(m7.loc["mono_metric", "abs_rel"] / m7.loc["mono_ft_lidar_all", "abs_rel"], 1))
            macro("VMEDRATIO", _fmt(float((ft / pre).median()), 2))

    if {"mono_ft_faro", "mono_ft_lidar"} <= set(m6.index):
        # the paper's headline ratio: how much of the laser teacher's benefit a LiDAR teacher keeps
        macro("FTTEACHERRATIO", _fmt(m6.loc["mono_ft_lidar", "chamfer"] / m6.loc["mono_ft_faro", "chamfer"], 2))
        macro("FTGAIN", _fmt(mean.loc["mono_metric", "chamfer"] / m6.loc["mono_ft_lidar", "chamfer"], 1))
        macro("FTGAPORACLE", _fmt((m6.loc["mono_ft_lidar", "chamfer"] - mean.loc["mono_oracle", "chamfer"]) * 100))

    # Exp4 (model size, oracle scale) and Exp3 (frame stride): both run the monocular model, so both
    # move whenever the depth code does -> macros rather than typed numbers (see git 48c1958).
    e4 = df[df.experiment == "exp4_model_size"].groupby("run_name").mean(numeric_only=True)
    e4sd = df[df.experiment == "exp4_model_size"].groupby("run_name").std(numeric_only=True)
    for run, tag in (("da_large", "DALARGE"), ("da_small", "DASMALL"), ("midas_small", "MIDAS")):
        if run not in e4.index:
            continue
        macro(f"{tag}CM", _fmt(e4.loc[run, "chamfer"] * 100, 2))
        macro(f"{tag}SD", _fmt(e4sd.loc[run, "chamfer"] * 100, 2))
        macro(f"{tag}F", _fmt(e4.loc[run, "fscore@0.05"], 2))
        macro(f"{tag}ABSREL", _fmt(e4.loc[run, "abs_rel"], 3))
        macro(f"{tag}DELTAONE", _fmt(e4.loc[run, "delta1"], 3))
        macro(f"{tag}SCAN", _fmt(e4.loc[run, "time_total_s"], 0))

    strides = (("s01", "ONE"), ("s05", "FIVE"), ("s10", "TEN"), ("s20", "TWENTY"))
    for exp, tag in (("exp3_frame_stride_gt", "STRGT"), ("exp3_frame_stride_oracle", "STRORACLE"),
                     ("exp3_frame_stride", "STRSCENE")):
        g = df[df.experiment == exp].groupby("run_name").mean(numeric_only=True)
        for run, word in strides:
            if run not in g.index:
                continue
            macro(f"{tag}{word}CM", _fmt(g.loc[run, "chamfer"] * 100))
            macro(f"{tag}{word}ACC", _fmt(g.loc[run, "accuracy"] * 100))
            macro(f"{tag}{word}COMP", _fmt(g.loc[run, "completeness"] * 100))
            macro(f"{tag}{word}F", _fmt(g.loc[run, "fscore@0.05"], 2))
            macro(f"{tag}{word}ABSREL", _fmt(g.loc[run, "abs_rel"], 3))
            macro(f"{tag}{word}N", _fmt(g.loc[run, "n_frames"], 0))
            macro(f"{tag}{word}SCAN", _fmt(g.loc[run, "time_total_s"], 0))

    Path(args.out).write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out} ({len(lines) - 2} macros)")


if __name__ == "__main__":
    main()
