"""Write paper/latex/numbers.tex: LaTeX macros (\\rs<NAME>) for headline numbers read from experiments/results.

    python scripts/paper_numbers.py [--results experiments/results] [--out paper/latex/numbers.tex]

Keeps the manuscript honest: every number that appears in prose more than once is a macro
generated from summary.csv, so re-running a sweep cannot leave a stale figure in the text.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


def _fmt(x: float, nd: int = 1) -> str:
    return f"{x:.{nd}f}"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="experiments/results")
    ap.add_argument("--out", default="paper/latex/numbers.tex")
    args = ap.parse_args()
    df = pd.read_csv(Path(args.results) / "summary.csv")
    e1 = df[df.experiment == "exp1_depth_source"].groupby("run_name")
    mean, std = e1.mean(numeric_only=True), e1.std(numeric_only=True)
    e5 = df[df.experiment == "exp5_lidar_confidence"].groupby("run_name").mean(numeric_only=True)

    def cm(run, col="chamfer"):
        return mean.loc[run, col] * 100, std.loc[run, col] * 100

    lines = ["% generated by scripts/paper_numbers.py — do not edit", ""]

    def macro(name, value):
        lines.append(f"\\newcommand{{\\rs{name}}}{{{value}}}")

    for run, tag in (("gt", "GT"), ("lidar", "LIDAR"), ("mono_oracle", "ORACLE"), ("mono_sparse", "SPARSE"),
                     ("mono_scene", "SCENE"), ("mono_metric", "METRIC")):
        if run not in mean.index:
            continue
        mu, sd = cm(run)
        macro(f"{tag}CM", _fmt(mu))
        macro(f"{tag}SD", _fmt(sd))
        macro(f"{tag}F", _fmt(mean.loc[run, "fscore@0.05"], 2))
        macro(f"{tag}ABSREL", _fmt(mean.loc[run, "abs_rel"], 3))
        macro(f"{tag}ACC", _fmt(mean.loc[run, "accuracy"] * 100))
        macro(f"{tag}COMP", _fmt(mean.loc[run, "completeness"] * 100))
        for tau, word in (("0.02", "two"), ("0.05", "five"), ("0.1", "ten")):   # no digits in macro names
            macro(f"{tag}F{word}", _fmt(mean.loc[run, f"fscore@{tau}"], 2))
            macro(f"{tag}R{word}", _fmt(mean.loc[run, f"recall@{tau}"], 2))
    if "mono_sparse" in mean.index:
        # per-scene Chamfer in the paper's Table 4.1 order -> \SPARSEa ... \SPARSEf ("—" if not run yet)
        order = ["42444474", "47333774", "47115299", "42897743", "47429736", "45261556"]
        sp = df[(df.experiment == "exp1_depth_source") & (df.run_name == "mono_sparse")]
        sp = sp.set_index(sp.scene.astype(str))["chamfer"]
        for letter, scene in zip("abcdef", order, strict=True):
            macro(f"SPARSE{letter}", _fmt(sp[scene] * 100) if scene in sp.index else "---")
        macro("SPARSEGAP", _fmt(cm("mono_sparse")[0] - cm("mono_oracle")[0]))
        macro("SPARSEGAPLIDAR", _fmt(cm("mono_sparse")[0] - cm("lidar")[0]))
        macro("SPARSEVSSCENE", _fmt(cm("mono_scene")[0] / cm("mono_sparse")[0]))
    for run, tag in (("lidar_conf1", "CONFONE"), ("lidar_conf2", "CONFTWO"),
                     ("lidar_w012", "WZOT"), ("lidar_w124", "WOTF")):
        if run in e5.index:
            macro(f"{tag}CM", _fmt(e5.loc[run, "chamfer"] * 100, 2))
            macro(f"{tag}F", _fmt(e5.loc[run, "fscore@0.05"], 2))
            macro(f"{tag}ACC", _fmt(e5.loc[run, "accuracy"] * 100, 2))
            macro(f"{tag}COMP", _fmt(e5.loc[run, "completeness"] * 100, 2))
    Path(args.out).write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out} ({len(lines) - 2} macros)")


if __name__ == "__main__":
    main()
